server:
  port: 7001

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_blog?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: fangzhi
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid

cloud-sso:
  server: http://localhost:9999
  logout:
    path: /logout
  excluded:
    paths:
  redis:
    address: redis://:fangzhi@localhost:6379

# aliyun oss
aliyun:
  oss:
    endpoint: your-config
    accessKeyId: your-config
    accessKeySecret: your-config
    bucketName: your-config
    policy:
      expire: 300 # 签名有效期（S）
    maxSize: 10 # 最大尺寸（M）
    callback: http://localhost:7001/aliyun/oss/callback
    dir:
      prefix: blog/images/ # 上传文件夹路径