server:
  port: 7001

spring:
  profiles:
    active: dev
  application:
    name: nacos-cloud-blog
  freemarker:
    request-context-attribute: request
    suffix: .html

# 需要用到的服务提供者配置
service-url:
  nacos-cloud-sso-service: http://nacos-cloud-sso

# mybatis
mybatis:
  mapper-locations: classpath*:xml/*.xml
  type-aliases-package: com.fangzhi.cloud.blog.dao.model
