server:
  port: 9999

spring:
  profiles:
    active: local
  application:
    name: nacos-cloud-sso
  freemarker:
    suffix: '.ftl'
    request-context-attribute: request
    settings.number_format: '0.##########'

# mybatis
mybatis:
  mapper-locations: classpath*:xml/*.xml
  type-aliases-package: com.fangzhi.cloud.sso.dao.model